---
- name: basic system setup
  hosts: all
  roles:
    - role: geerlingguy.security
      vars:
        security_fail2ban_enabled: true
      become: true
  tasks:
    - name: configure journald to persist logs
      lineinfile:
        path: /etc/systemd/journald.conf
        regex: ^(# *)?Storage\b
        line: Storage=persistent
      become: true
    - name: configure journald to compress logs
      lineinfile:
        path: /etc/systemd/journald.conf
        regex: ^(# *)?Compress\b
        line: Compress=yes
      become: true
    - name: configure journald to store at most 10GB of logs
      lineinfile:
        path: /etc/systemd/journald.conf
        regex: ^(# *)?SystemMaxUse\b
        line: SystemMaxUse=10G
      become: true
    - name: configure journald to store at most 10GB of logs
      lineinfile:
        path: /etc/systemd/journald.conf
        regex: ^(# *)?SystemMaxUse\b
        line: RuntimeMaxUse=10G
      become: true
    - name: configure journald to keep 2GB free
      lineinfile:
        path: /etc/systemd/journald.conf
        regex: ^(# *)?SystemKeepFree\b
        line: SystemKeepFree=2G
      become: true
    - name: configure journald to keep 2GB free
      lineinfile:
        path: /etc/systemd/journald.conf
        regex: ^(# *)?RuntimeKeepFree\b
        line: RuntimeKeepFree=2G
      become: true
    - name: enable & start journald
      ansible.builtin.shell: |
        systemctl daemon-reload
        systemctl restart systemd-journald
      become: true

    # configure firewall
    - name: put fail2ban config
      ansible.builtin.copy:
        src: lib/fail2ban-jail.local
        dest: /etc/fail2ban/jail.local
      become: true
    - name: reload & restart fail2ban
      ansible.builtin.shell: |
        fail2ban-client reload
        fail2ban-client restart
      become: true
    - name: let UFW deny everything
      community.general.ufw:
        policy: deny
      become: true
    - name: let UFW allow rate-limited SSH
      community.general.ufw:
        rule: limit
        name: OpenSSH
      become: true
    - name: enable UFW
      community.general.ufw:
        state: enabled
      become: true
