---
- name: basic system setup
  hosts: all
  roles:
    - role: geerlingguy.security
      vars:
        security_fail2ban_enabled: true
      become: true
  tasks:
    # update all packages
    - name: apt update
      ansible.builtin.apt:
        update_cache: true
      become: true
    - name: apt upgrade && apt autoremove
      ansible.builtin.apt:
        name: '*'
        state: latest
        autoremove: true
      become: true
    # todo: upgrade OS unattended? e.g. `do-release-upgrade`?
    # see also https://www.jeffgeerling.com/blog/2018/ansible-playbook-upgrade-all-ubuntu-1204-lts-hosts-1404-or-1604-1804-etc
    # - name: apt dist-upgrade
    #   ansible.builtin.apt:
    #     upgrade: dist
    #   become: true

    # todo:
    # unattended upgrades
    # sudo apt install -y net-tools

    - name: set hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname | replace('_','-') }}"

    - name: configure journald to persist logs
      lineinfile:
        path: /etc/systemd/journald.conf
        regex: ^(# *)?Storage\b
        line: Storage=persistent
      become: true
    - name: configure journald to compress logs
      lineinfile:
        path: /etc/systemd/journald.conf
        regex: ^(# *)?Compress\b
        line: Compress=yes
      become: true
    - name: configure journald to store at most {{ journald_system_max_use }} of logs
      lineinfile:
        path: /etc/systemd/journald.conf
        regex: ^(# *)?SystemMaxUse\b
        line: SystemMaxUse={{ journald_system_max_use }}
      become: true
    - name: configure journald to store at most {{ journald_runtime_max_use }} of logs
      lineinfile:
        path: /etc/systemd/journald.conf
        regex: ^(# *)?SystemMaxUse\b
        line: RuntimeMaxUse={{ journald_runtime_max_use }}
      become: true
    - name: configure journald to keep {{ journald_system_keep_free }} free
      lineinfile:
        path: /etc/systemd/journald.conf
        regex: ^(# *)?SystemKeepFree\b
        line: SystemKeepFree={{ journald_system_keep_free }}
      become: true
    - name: configure journald to keep {{ journald_runtime_keep_free }} free
      lineinfile:
        path: /etc/systemd/journald.conf
        regex: ^(# *)?RuntimeKeepFree\b
        line: RuntimeKeepFree={{ journald_runtime_keep_free }}
      become: true
    - name: systemd daemon-reload, enable & restart journald
      ansible.builtin.systemd_service:
        daemon_reload: true
        enabled: true
        state: restarted
        name: journald
      become: true
