---
- name: basic system setup
  hosts: all
  roles:
    - role: geerlingguy.security
      vars:
        security_fail2ban_enabled: true
        security_ssh_password_authentication: 'yes'
        security_ssh_permit_root_login: 'yes'
        security_fail2ban_custom_configuration_template: '../templates/fail2ban-ssh.local.j2'
      become: true

    - name: install Prometheus node exporter
      role: prometheus.prometheus.node_exporter
      vars:
        node_exporter_enabled_collectors:
          # > Collectors are enabled by providing a `--collector.<name>` flag. Collectors that are enabled by default can be disabled by providing a `--no-collector.<name>` flag. To enable only some specific collector(s), use `--collector.disable-defaults --collector.<name> ...`.
          # – https://github.com/prometheus/node_exporter/blob/v1.8.2/README.md#collectors
          - disable-defaults
          - cpu
          - diskstats
          - filesystem
          - hwmon
          - loadavg
          - meminfo
          - netdev
          - systemd
        # default is `0.0.0.0:9100`
        node_exporter_web_listen_address: "{{ wireguard_addresses.0.split('/')[0] }}:{{ prometheus_node_exporter_port }}"

    # todo: remove in favor of Node Exporter's `systemd` collector – does this work?
    # see https://github.com/prometheus/node_exporter/blob/v1.8.2/collector/systemd_linux.go#L158-L174
    - name: install Prometheus systemd exporter
      role: prometheus.prometheus.systemd_exporter
      vars:
        systemd_exporter_enable_restart_count: true
        # default is `0.0.0.0:9558`
        systemd_exporter_web_listen_address: "{{ wireguard_addresses.0.split('/')[0] }}:{{ prometheus_systemd_exporter_port }}"
  tasks:
    # update all packages
    - name: apt update
      ansible.builtin.apt:
        update_cache: true
      become: true
    - name: apt upgrade && apt autoremove
      ansible.builtin.apt:
        name: '*'
        state: latest
        autoremove: true
      become: true
    # todo: upgrade OS unattended? e.g. `do-release-upgrade`?
    # see also https://www.jeffgeerling.com/blog/2018/ansible-playbook-upgrade-all-ubuntu-1204-lts-hosts-1404-or-1604-1804-etc
    # - name: apt dist-upgrade
    #   ansible.builtin.apt:
    #     upgrade: dist
    #   become: true

    # todo: timedatectl set-ntp true
    - name: set timezone to Europe/Berlin
      become: true
      community.general.timezone:
        name: Europe/Berlin

    - name: install basic packages
      ansible.builtin.apt:
        name:
          - findutils # provides `find` & `xargs`, among others
          - jq
          - mosh
          - net-tools # provides `netstat`, among others
          - pv
          - screen
          - tree
      become: true

    - name: let UFW deny everything
      community.general.ufw:
        policy: deny
      become: true
    - name: let UFW allow rate-limited SSH
      community.general.ufw:
        rule: limit
        name: OpenSSH
      become: true
    - name: let UFW allow rate-limited Mosh
      community.general.ufw:
        rule: limit
        name: mosh
      become: true
    - name: let UFW always allow SSH from chestnut.jannisr.de
      community.general.ufw:
        rule: allow
        src: '{{ item }}'
        name: OpenSSH
      become: true
      loop: '{{ ssh_allowed_ips }}'
    - name: let UFW always allow Mosh from chestnut.jannisr.de
      community.general.ufw:
        rule: allow
        src: '{{ item }}'
        name: mosh
      become: true
      loop: '{{ ssh_allowed_ips }}'
    - name: enable UFW
      community.general.ufw:
        state: enabled
      become: true

    - name: set hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname | replace('_','-') }}"
      become: true

    - name: configure journald to persist logs
      lineinfile:
        path: /etc/systemd/journald.conf
        regex: ^(# *)?Storage\b
        line: Storage=persistent
      become: true
    - name: configure journald to compress logs
      lineinfile:
        path: /etc/systemd/journald.conf
        regex: ^(# *)?Compress\b
        line: Compress=yes
      become: true
    - name: configure journald to store at most {{ journald_system_max_use }} of logs
      lineinfile:
        path: /etc/systemd/journald.conf
        regex: ^(# *)?SystemMaxUse\b
        line: SystemMaxUse={{ journald_system_max_use }}
      become: true
    - name: configure journald to store at most {{ journald_runtime_max_use }} of logs
      lineinfile:
        path: /etc/systemd/journald.conf
        regex: ^(# *)?SystemMaxUse\b
        line: RuntimeMaxUse={{ journald_runtime_max_use }}
      become: true
    - name: configure journald to keep {{ journald_system_keep_free }} free
      lineinfile:
        path: /etc/systemd/journald.conf
        regex: ^(# *)?SystemKeepFree\b
        line: SystemKeepFree={{ journald_system_keep_free }}
      become: true
    - name: configure journald to keep {{ journald_runtime_keep_free }} free
      lineinfile:
        path: /etc/systemd/journald.conf
        regex: ^(# *)?RuntimeKeepFree\b
        line: RuntimeKeepFree={{ journald_runtime_keep_free }}
      become: true
    - name: systemd daemon-reload, enable & restart systemd-journald
      ansible.builtin.systemd_service:
        daemon_reload: true
        enabled: true
        state: restarted
        name: systemd-journald
      become: true
